### ISSUE TITLE
Failed to prepare live with Chrome ver.39(64bit)

### ISSUE THREAD

**Issue by theOrangest** [honishi/Hakumai#1]
comment says "Failed to prepare live.(notlogin)"

OSX ver.10.0.2
Chrome ver. 39.0.2171.95 (64-bit)

**Comment by honishi** [comment]
Thanks for evaluating Hakumai and posting issue.

The status `notlogin` is an internal response code of niconico's `getplayerstatus` api. So I guess Hakumai could not get proper cookie from Chrome's cookie store.

Currently Hakumai uses the cookie in following location.

```
~/Library/Application Support/Google/Chrome/Default/Cookies
```

If you create user in Chrome, the cookie store's location for your niconico account might be different. :tired_face:

I continue investigation of this, but if you know anything about this, please let me know.

Thanks.

**Comment by honishi** [comment]
Fixed in https://github.com/honishi/Hakumai/commit/18d761f230576d7e590bd417682ac55be92c8d78.
