### ISSUE TITLE
[Proposal] Add optional button to enable comment_speak for 184 comment

### ISSUE THREAD

**Issue by ghost** [honishi/Hakumai#12]
Hi, thank you for this great oss. I use everyday.
I want to enable comment_speak for 184 comments, and I believe some people need it as well.

I think I should add `ippan_transparent` to below,

https://github.com/honishi/Hakumai/blob/1f1221c81fac0e268613850bbefc45878d12b131/Hakumai/Managers/SpeechManager/SpeechManager.swift#L101

and add some flag to below.

https://github.com/honishi/Hakumai/blob/1f1221c81fac0e268613850bbefc45878d12b131/Hakumai/Storyboards/PreferenceWindowController.storyboard#L138-L147

However sorry I don't know how to contribute to Swift project. So I'll be glad if you can add this option someday when you have a time.

**Comment by honishi** [comment]
Thanks for the proposal.
Let me check. :pray:

**Comment by honishi** [comment]
ご提案ありがとうございます。（日本語ですみません。）

ご指摘の `.ippanTransparent` なコメントですが、こちら 2020 年頃？に途中で追加になった enum 値で、本来であれば 184 コメントの一部として前述の guard 句の中に入れることで、そもそもコメント読み上げの対象とするべきでした。（オプションの flag とかなしで）

ただ、そもそも `.ippanTransparent` なコメントは、コメントの流量が多くなってきた際に 184 コメントを透明に表示するためにコメントサーバーで付与される premium 値なので、読み上げの対象にしても（コメントの流量が多くて）読み上げスキップの挙動になってしまうかもしれません。

・・いったん上記のように考えているのですが、ulwlu さんが解決したい状況は上記と同じでしょうか？
私がユーザー生放送しか見ないので、なにか見落としがあるかもしれず。。念のため、確認させていただければと思います。:pray:

**Comment by ghost** [comment]
ご確認くださりありがとうございます。

はい、私の解決したい状況は、過不足なく仰る通りです。

確かにそのような挙動になってしまう可能性も承知致しました。

**Comment by honishi** [comment]
ご確認どうもありがとうございます。
それでは今週中目処で更新してリリースしますので、少々お待ち下さい。
ありがとうございます。:pray:

**Comment by ghost** [comment]
ご返信・ご対応ありがとうございます！よろしくお願い致します。

**Comment by honishi** [comment]
https://github.com/honishi/Hakumai/commit/306f6e4b00f257d5e37671ca1956f683daa4673d で対応してリリースしました。:pray:

**Comment by ghost** [comment]
ありがとうございました！
これからも利用していき、他の人にも勧めてみます！
