### ISSUE TITLE
Add button to download all comments

### ISSUE THREAD

**Issue by iklam** [honishi/Hakumai#14]
Hello, I really like your software. Is it possible to add a button to download all the comments? This is especially useful when viewing a timeshift stream.

FYI,  NCV (https://www.posite-c.com/application/ncv/) has the following buttons:
- Get the previous 200 comments
- Get all previous comments

Thanks

**Comment by honishi** [comment]
Thanks for the feedback.
The feature you've mentioned is what I'm also wanting.
So let me put the feature onto my todo tasks.

Thanks!

**Comment by honishi** [comment]
For now, I've just implemented and released v0.98.0 which automatically receives all comments from time shift program.
It's really rough implementation, so let me improve and refine the feature and user interface from now on.
Anyway, please check v0.98.0 app.
Thanks.
