### ISSUE TITLE
バックステージパスを所有している放送でFailed to prepare live.

### ISSUE THREAD

**Issue by misterT2525** [honishi/Hakumai#2]
自分がバックステージパスを所有している放送のコメントを取得しようとした時に`Failed to prepare live.(error in extracting getplayerstatus response)`と言われて取得出来ないです  
自分の推測ですが、座席番号が"バックステージパス - －"になっており、部屋を取得出来ないからだと思われます
##### 環境
- OS X Yosemite 10.10.3 (14D136)
- Google Chrome 43.0.2357.81
- Hakumai 0.0.18 (1015)

**Comment by honishi** [comment]
情報ありがとうございます。

どこのBSPも持っていないのでテストができていないのですが、ご指摘の内容で修正を入れてみました。(https://github.com/honishi/Hakumai/commit/a1fbb01cf4dab16f397f9e1dad87851c8a2940d5)

バイナリを更新していますので、お手すきの際に Check for Updates で試してみていただければと思います。

**Comment by misterT2525** [comment]
Hakumai 0.0.19 (1016)にてBSPを所有している放送を開いたところ、Hakumaiが予期しない理由で終了しました。

**Comment by honishi** [comment]
なるほど・・。ご確認ありがとうございます。手元に再現環境がないのでなかなか厳しいですね。。

ちょっとどこまで解析できるかわかりませんが、`getplayerstatus` のレスポンスを見させてもらっていいでしょうか？　アプリのログを吐くバイナリを以下に置きましたので、使っていただければと。
- https://hakumai.s3.amazonaws.com/Hakumai.0.0.19.debug.zip
  - 「開発元が未確認のため開けません」になると思うので、.app を右クリックで「開く」してください。

```
cd ~/Library/Application\ Support/com.honishi.Hakumai
cat Hakumai_Api.log
```

これでアプリを動かして、`Hakumai_Api.log` の上の方に出てるはずの `getplayerstatus` のレスポンスを見させていただければと。
（`<user />` のあたりが個人情報っぽくなっていますので、もしあれでしたらお手数ですが適当にマスクお願いします。）

あと、「予期せぬ理由で終了」のときに error stack みたいのが画面に出ていたら、それも貰えれば助かります。:bow:

**Comment by misterT2525** [comment]
コンソールからHakumai.app/Contents/MacOS/Hakumaiを起動して放送を開いたときのログ、予期せぬ理由で終了した時のAppleへのレポート、getplayerstatusのレスポンスのtokenっぽい奴だけマスクした物を以下のgistにアップロードしました。

gistのリンクはもしも個人情報が残ってた場合に困るので削除しました

**Comment by honishi** [comment]
ログの提供、ありがとうございます。（マスクもお手数おかけしました）

いただいたコンソールログと `getplayerstatus` のレスポンスから、必ず落ちる条件がひとつあったので、それを修正してみました。（座席番号 `<room_seetno />` が数字ではない場合、内部的な扱いが nil になるのですが、そのままだと画面描画や追い出しが nil を想定しておらずアプリが落ちるので、そのような場合は暫定的に -1 として処理する）
- https://hakumai.s3.amazonaws.com/Hakumai.0.0.19.debug2.zip
  - https://github.com/honishi/Hakumai/tree/feature/fix-bsp-crash

度々すみませんが、お手すきの際に試していただければと思います。

**Comment by misterT2525** [comment]
コメントの取得まで正常に動作しました。ありがとうございます。
自分はいつもコメントするのはブラウザでやっているので問題無いのですが、試しにHakumaiからコメント送信を試したところ、BSPコメント以外のコメントも送信が出来ません。

**Comment by honishi** [comment]
早速の確認どうもありがとうございます。

BSPコメントの送信については、コメントサーバーへコメントを送るときの `<chat />` エレメントにBSPコメントかどうかを示す属性を１つ追加すればいいだけなのですが（たしか）、テストする環境がないので、いったん保留中、みたいなステータスです。

**Comment by misterT2525** [comment]
ブラウザからBSPコメントを送信するときは`http://live.nicovideo.jp/api/presscast`にPOSTしているようです。(`watch_ginza_cb.js`の18行目に処理が書かれている模様)
たぶんpremium属性の問題だと思うのですが、BSPコメントではない普通にコメントも送信出来ません。

**Comment by honishi** [comment]
おっと、「BSPコメント以外のコメントも送信が出来ません」ということですね。読み違えてました。
ちょっと時間のあるときに見ておきます。

**Comment by honishi** [comment]
暫定的に v0.0.20 (1017) にて、BSP 所有時はそもそもコメントを打ち込めないようにしました。(text field を disable に)

**Comment by honishi** [comment]
そもそも BSP という概念が消滅してしまったので、close します。:pray:
