### ISSUE TITLE
ChromeのCookieが読み込めない

### ISSUE THREAD

**Issue by Econa77** [honishi/Hakumai#9]
ChromeのCookieを読み込むことができませんでした。
確認したところ
`~/Library/Application Support/Google/Chrome/Default/Cookies`
にクッキーが存在しているのはChromeにGoogleアカウントが１つ以上紐づいている場合のみで、未ログインの場合は
`~/Library/Application Support/Google/Chrome/Profile 1/Cookies`
に作成されているようです。

Related #1

**Comment by honishi** [comment]
詳細にありがとうございます。
のちほど対応します。

**Comment by honishi** [comment]
OAuth 対応によりそもそも Cookie を使わなくなったので、close します。:pray:
